### ISSUE TITLE
Markdown rel parsing regex and messy input

### ISSUE THREAD

**Issue by distobj** [uogbuji/versa#17]
I'm running into issues with Versa choking on irregular and malformed input during markdown parsing. The properties contain embedded HTML. It appears as though REL_PAT in markdown_parse.py takes the less-than symbol to indicate that the property value is an IRIref and so tries to do linky things with the value and a base, usually failing and resulting in a discarded record.

I've attached a sample unpaywall record.

[unpay-badtitle.txt](https://github.com/uogbuji/versa/files/5562804/unpay-badtitle.txt)

**Comment by uogbuji** [comment]
Hi @distobj what you attached is JSON rather than Versa Literate/Markdown. Can you attach the latter so I can see the problem clearly? Thanks.

**Comment by uogbuji** [comment]
A discussion with @distobj clarified this, and I've pushed a fix so the user doesn't have to escape this case.
