### ISSUE TITLE
new-entity-hook not being used. context issue?

### ISSUE THREAD

**Issue by distobj** [uogbuji/versa#18]
In the attached test case for the pipeline-uni branch (I started from test_pipeline), you can see that the new-entity-hook isn't being called.

[test_newentity_context_bug.txt](https://github.com/uogbuji/versa/files/5704538/test_newentity_context_bug.txt)

**Comment by uogbuji** [comment]
Yup. Multiple new entity hooks weren't properly supported. Sorry about the delay. I fixed this yesterday, but then got myself into an undisciplined code-clean-up rabbit hole (slight oxymoron there :) ). To avoid further delay I cherry-picked the heart of the fix and I can keep on working on that clean-up for a subsequent push.
