### ISSUE TITLE
Implement less finicky parser for Versa literate

### ISSUE THREAD

**Issue by uogbuji** [uogbuji/versa#29]
The current vlit parser, in `markdown_parse.py`, is very finicky with respect to special characters that delimit Markdown format. It delegates to PyMarkdown, and then interprets the HTML result.

We want a native parser for Versa literate, which, though based on Markdown, is really its own language. This will release users from gymnastics to make sure parse inout is Markdown safe.

**Comment by uogbuji** [comment]
Done & merged into develop.

**Comment by uche-eis** [comment]
Released

**Comment by uogbuji** [comment]
https://github.com/uogbuji/versa/releases/tag/0.8.9
