### ISSUE TITLE
materialize inverse feature creates both inverse and forward statements

### ISSUE THREAD

**Issue by distobj** [uogbuji/versa#6]
When materializing with inverse=True, both forward and inverse statements between the origin and materialized resource are created. In the inverse-fix branch, I used an approach that passes the rels being inverted to the outer context so that the caller can avoid creating the forward rels, but other solutions might be more desirable.

**Comment by uogbuji** [comment]
I ended up replacing the `inverse` flag altogether. First of all with `materialize(link=` you can now specify a full origin, rel, target triple. In addition, there is an `attach` flag, which allows you to turn off the automatic attachment of a newly materialized resource to the context.

**Comment by uogbuji** [comment]
Left open pending merge to master

**Comment by distobj** [comment]
Since this is still open, I'll mention the regression that was observed today here.

Some properties - i've been unable determine exactly which, but it's deterministic - are superceded by their input model short names (grounded in whatever base namespace is defined).

**Comment by uogbuji** [comment]
Making sure I follow. Properties supplied by `materialize`/`links`?

**Comment by uogbuji** [comment]
This has been sorted with the `attach=True` param, and ability to create fully-defined links.
